export const DEFAULT_CHECKLIST = [
  { g: '18+ meses antes', c: '18 meses antes', n: 'Fijar fecha de la boda', p: 'urgente' as const, nota: 'Consultar disponibilidad con familia' },
  { g: '18+ meses antes', c: '18 meses antes', n: 'Definir presupuesto total', p: 'urgente' as const, nota: 'Incluir anillos, luna de miel, vestido' },
  { g: '18+ meses antes', c: '18 meses antes', n: 'Hacer lista inicial de invitados', p: 'urgente' as const, nota: 'Lista A (seguros) y lista B' },
  { g: '18+ meses antes', c: '16 meses antes', n: 'Visitar y reservar la finca', p: 'urgente' as const, nota: 'Pedir contrato y política de cancelación' },
  { g: '18+ meses antes', c: '16 meses antes', n: 'Contratar al fotógrafo', p: 'urgente' as const, nota: 'Los buenos se reservan con antelación' },
  { g: '18+ meses antes', c: '15 meses antes', n: 'Contratar al videógrafo', p: 'urgente' as const, nota: 'Pedir vídeos de referencia' },
  { g: '18+ meses antes', c: '14 meses antes', n: 'Buscar y reservar catering', p: 'urgente' as const, nota: 'Pedir al menos 3 presupuestos' },
  { g: '12 meses antes', c: '12 meses antes', n: 'Empezar búsqueda del vestido', p: 'urgente' as const, nota: 'Fabricación de 6-9 meses' },
  { g: '12 meses antes', c: '12 meses antes', n: 'Buscar y reservar DJ o banda', p: 'urgente' as const, nota: 'Compartir lista de canciones vetadas' },
  { g: '12 meses antes', c: '12 meses antes', n: 'Contratar al oficiante', p: 'urgente' as const, nota: 'Reunión inicial de estilo' },
  { g: '12 meses antes', c: '12 meses antes', n: 'Definir estilo y paleta de colores', p: 'pronto' as const, nota: 'Influye en flores y papelería' },
  { g: '12 meses antes', c: '11 meses antes', n: 'Enviar save-the-date', p: 'pronto' as const, nota: 'Importante si hay invitados de fuera' },
  { g: '12 meses antes', c: '10 meses antes', n: 'Buscar y reservar florista', p: 'pronto' as const, nota: 'Pedir bocetos del ramo' },
  { g: '12 meses antes', c: '10 meses antes', n: 'Buscar traje del novio', p: 'pronto' as const, nota: 'Alquiler o compra con antelación' },
  { g: '9 meses antes', c: '9 meses antes', n: 'Diseñar y encargar invitaciones', p: 'pronto' as const, nota: 'Incluir RSVP y mapa' },
  { g: '9 meses antes', c: '9 meses antes', n: 'Reservar hotel noche de bodas', p: 'pronto' as const, nota: 'Suite nupcial con extras' },
  { g: '9 meses antes', c: '9 meses antes', n: 'Gestionar alojamiento invitados', p: 'pronto' as const, nota: 'Negociar precio grupal' },
  { g: '9 meses antes', c: '8 meses antes', n: 'Contratar empresa de autobuses', p: 'pronto' as const, nota: 'Definir rutas y horarios' },
  { g: '9 meses antes', c: '8 meses antes', n: 'Reservar coche nupcial', p: 'pronto' as const, nota: 'Confirmar trayecto completo' },
  { g: '9 meses antes', c: '8 meses antes', n: 'Contratar empresa de decoración', p: 'pronto' as const, nota: 'Centros de mesa, arco floral' },
  { g: '6 meses antes', c: '6 meses antes', n: 'Enviar invitaciones formales', p: 'pronto' as const, nota: 'Con fecha límite de RSVP' },
  { g: '6 meses antes', c: '6 meses antes', n: 'Organizar lista de bodas', p: 'normal' as const, nota: 'Tienda, plataforma o viaje' },
  { g: '6 meses antes', c: '6 meses antes', n: 'Primera prueba del vestido', p: 'urgente' as const, nota: 'Llevar zapatos definitivos' },
  { g: '6 meses antes', c: '6 meses antes', n: 'Prueba de menú con el catering', p: 'urgente' as const, nota: 'Asistir los dos novios' },
  { g: '6 meses antes', c: '5 meses antes', n: 'Contratar maquilladora y peluquería', p: 'pronto' as const, nota: 'Hacer prueba antes del día' },
  { g: '6 meses antes', c: '5 meses antes', n: 'Confirmar padrinos y testigos', p: 'pronto' as const, nota: 'Comunicarles sus roles' },
  { g: '6 meses antes', c: '5 meses antes', n: 'Trabajar los votos', p: 'pronto' as const, nota: 'Escribir el discurso' },
  { g: '6 meses antes', c: '5 meses antes', n: 'Contratar animación infantil', p: 'normal' as const, nota: 'Si hay niños en la boda' },
  { g: '3 meses antes', c: '3 meses antes', n: 'Confirmar número definitivo de invitados', p: 'urgente' as const, nota: 'Comunicar al catering y finca' },
  { g: '3 meses antes', c: '3 meses antes', n: 'Distribución definitiva de mesas', p: 'urgente' as const, nota: 'Comunicar intolerancias' },
  { g: '3 meses antes', c: '3 meses antes', n: 'Comprar detalles para invitados', p: 'pronto' as const, nota: 'Personalizar si es posible' },
  { g: '3 meses antes', c: '3 meses antes', n: 'Tramitar certificado de matrimonio', p: 'urgente' as const, nota: 'Cita en juzgado o registro' },
  { g: '3 meses antes', c: '2 meses antes', n: 'Reunión final con el catering', p: 'urgente' as const, nota: 'Menú definitivo e intolerancias' },
  { g: '3 meses antes', c: '2 meses antes', n: 'Reunión final con la finca', p: 'urgente' as const, nota: 'Plano, horarios y accesos' },
  { g: '3 meses antes', c: '2 meses antes', n: 'Briefing con fotógrafo y videógrafo', p: 'pronto' as const, nota: 'Lista de fotos obligatorias' },
  { g: '3 meses antes', c: '2 meses antes', n: 'Contratar seguro de boda', p: 'pronto' as const, nota: 'Cubre cancelaciones y lluvia' },
  { g: '1 mes antes', c: '1 mes antes', n: 'Segunda prueba del vestido', p: 'urgente' as const, nota: 'Ajuste final con accesorios' },
  { g: '1 mes antes', c: '1 mes antes', n: 'Confirmar todos los proveedores', p: 'urgente' as const, nota: 'Llamada para confirmar hora' },
  { g: '1 mes antes', c: '1 mes antes', n: 'Preparar sobres de propinas', p: 'pronto' as const, nota: 'Efectivo listo para el día' },
  { g: '1 mes antes', c: '3 semanas antes', n: 'Ensayo de la ceremonia', p: 'urgente' as const, nota: 'Con oficiante y participantes' },
  { g: '1 mes antes', c: '2 semanas antes', n: 'Hacer el guión definitivo del día', p: 'urgente' as const, nota: 'Compartir con proveedores' },
  { g: '1 mes antes', c: '2 semanas antes', n: 'Preparar maleta de luna de miel', p: 'normal' as const, nota: 'Pasaportes y reservas' },
  { g: '1 mes antes', c: '1 semana antes', n: 'Manicura y pedicura', p: 'normal' as const, nota: 'Coordinar con el ramo' },
  { g: '1 mes antes', c: '3 días antes', n: 'Recoger el vestido definitivo', p: 'urgente' as const, nota: 'Colgar en lugar fresco' },
  { g: '1 mes antes', c: '1 día antes', n: 'Preparar detalles para el día B', p: 'urgente' as const, nota: 'Anillos, arras, discursos' },
  { g: 'El día de la boda', c: 'El día', n: 'Kit de emergencia de la novia', p: 'urgente' as const, nota: 'Imperdibles, quitamanchas, aguja' },
  { g: 'El día de la boda', c: 'El día', n: 'Designar contacto con proveedores', p: 'urgente' as const, nota: 'Familiar de confianza' },
  { g: 'El día de la boda', c: 'El día', n: 'Entregar sobres de propinas', p: 'urgente' as const, nota: 'Al final de cada servicio' },
  { g: 'El día de la boda', c: 'El día', n: 'Guardar el ramo si se conserva', p: 'normal' as const, nota: 'Preservación floral' },
  { g: 'Después de la boda', c: '1 semana después', n: 'Enviar notas de agradecimiento', p: 'pronto' as const, nota: 'A quienes ayudaron' },
  { g: 'Después de la boda', c: '1 mes después', n: 'Cambio de apellidos', p: 'pronto' as const, nota: 'DNI, pasaporte, banco' },
  { g: 'Después de la boda', c: '1 mes después', n: 'Recibir y revisar fotos y vídeo', p: 'normal' as const, nota: 'Copia de seguridad doble' },
  { g: 'Después de la boda', c: '2 meses después', n: 'Elegir álbum de fotos', p: 'normal' as const, nota: 'Varias opciones del fotógrafo' },
]